INSERT INTO adj_chatbot(id_articulo, texto)
VALUES
    (101, 'Para licitar, haz clic en la sección correspondiente presente en cada oferta. Tu puja tiene que ser menor a la puja más baja actual. Tras introducir el valor, pulsa Confirmar.'),
    (201, 'Per licitar, fes clic a la secció corresponent present a cada oferta. La teva puja ha de ser inferior a la mes baixa actual. Després d’introduir el valor, prem “Confirmar”. '),
    (301, 'To bid, click the corresponding section present in every offer. Your bid has to be higher than the current lowest one. After imputting the value, press “Confirm”. '),
    (102, 'Para guardar una oferta como favorita, haz clic en el corazón presente en la oferta. Las ofertas marcadas como favorito se mostrarán en secciones especiales.'),
    (202, 'Per guardar una oferta com a favorit, fes clic al cor present a la oferta. Les ofertes marcades com a favorites es mostraran a seccions especials. '),
    (302, 'To save an offer as a favorite, click the heart present in the offer. Offers marked this way will show in special sections. '),
    (103, 'Para consultar y editar tu perfil, lo puedes hacer desde el botón Perfil del menú fijo. Para consultar el perfil de una empresa, lo puedes hacer desde una ventana de chat o desde una oferta. '),
    (203, 'Per a consultar i editar el teu perfil, ho pots fer desde el botó Perfil del menú fixe. Per consultar el perfil d’una empresa, ho pots fer desde la ventana de xat o des d’una oferta. '),
    (303, 'To check or edit your own profile, you can do so through the Profile icon in the fix menu bar. In order to check a company’s profile, you can do so through a chat window or through an offer screen.'),
    (104, 'Para valorar a una empresa privada o a un organismo público, puedes hacerlo desde el perfil de esta. Podrás valorarles sobre cinco estrellas y dejar un comentario. Todas las valoraciones son publicas. '),
    (204, 'Per valorar una empresa o organisme públic, pots fer-ho desde el perfil d´aquesta. Podras valorar-les sobre cinc estrelles i deixar un comentari. Totes les valoracions son publiques.'),
    (304, 'In order to rate a company or public organism, you can do so through their profile. You can rate them out of five stars and leave a comment. All ratings are public to anyone.'),
    (105, 'Para editar los ajustes de la aplicación, puedes hacerlo desde el menú Perfil, y posteriormente eligiendo la opción que desees editar.'),
    (205, 'Per a editar les opcions de l’aplicació, pots fer-ho desde el menú Perfil i, posteriorment, escollint l´opció que vulguis editar.'),
    (305, 'In order to edit the app’s settings, you can do so through the Profile menu. After getting there, choose the option you wish to edit.'),
    (106, 'Para cambiar de idioma, puedes hacerlo desde la opción correspondiente de los ajustes. La app se ofrece en 3 idiomas; español, catalán e inglés. '),
    (206, 'Per a canviar d’idioma, ho pots fer desde l’opció corresponent dels ajustos. L´app s’ofereix en 3 idiomes diferents; castellà, català o anglès. '),
    (306, 'In order to change the app’s language, click the corresponding option in Settings. The app’s offered in three different languages; Spanish, English or Catalan. '),
    (107, 'Para buscar con filtros, elige las opciones deseadas antes de emitir tu búsqueda. Puedes filtrar por diversos parámetros.'),
    (207, 'Per a emprar filtres a la cerca, escull les opcions desitjades abans d´emetre la teva cerca. Pots filtrar per diversos paràmetres.'),
    (307, 'In order to apply filters to your search, choose the corresponding options before submitting your query. Several filtering options are available.'),
    (108, 'AdjudiCat tiene implementada la sincronización con el calendario de Google. Ciertas fechas señaladas de cada licitación se añadirán automáticamente a este calendario. Es necesario un login de Google para sincronizar.'),
    (208, 'AdjudiCat implementa la sincronització amb el calendari de Google. Certes dates importants de cada licitació s´afegiran al calendari de Google. Es necessari un login amb Google per emprar aquesta funcionalitat.'),
    (308, 'Our application implements synchronization with Google calendar. Some important dates on each bid will be added to your personal Google calendar. A google login must be done for this to be used.'),
    (109, 'Para abrir el mapa, puedes hacerlo desde la barra de búsquedas. Se abrirá la localización de dicha entidad, o un mapa para buscar por cercanía, dependiendo del caso.'),
    (209, 'Per obrir el mapa, es pot fer desde la barra de cerca. Es pot cercar ofertes properes a l´usuari o veure l´ubicació on es durà a terme una licitació.'),
    (309, 'To open the map, you can do so through the search bar. You can search for nearby offers or see the location on which the offer will be held.'),
    (110, 'Una cuenta puede ser bloqueada por los administradores o por logins fallidos. Si tu cuenta está bloqueada, espera 24 horas para intentar logearte de nuevo. '),
    (210, 'Un compte pot ser bloquejat pels administradors o per logins fallits. Si el teu compte esta bloquejat, espera 24 hores per intentar-ho de nou. '),
    (310, 'An account can be manually blocked by the administrators or by repeatedly failing a login. If your account ever was blocked, wait 24 hours before trying to log in again. '),
    (111, 'Para cambiar tu contraseña, lo puedes hacer desde el menú Perfil. Debes introducir tu contraseña anterior para poder actualizarla. Esto solo está disponible para cuentas de AdjudiCat, no de Google.'),
    (211, 'Per a canviar la teva contrasenya, ho pots fer desde el menú Perfil. Has d´introduir la teva contrasenya anterior per a poder actualitzar-la. Aixó tan sols és disponible per a comptes d´AdjudiCat, no de Google.'),
    (311, 'In order to change your password, you can do so through the Profile tab. You must input your old password to be able to change it. Only AdjudiCat accounts can perform this action.'),
    (112, 'Puedes ver los locales vacíos en cuanto acabe tu licitación desde el botón correspondiente, para poder concertar un evento de apertura. Se mostrarán todos los eventos en un rango.'),
    (212, 'Pots veure els locals buits en quan acabi la teva licitació creada desde el botó corresponent per a concertar un event d´apertura. Es mostraran tots els events en un rang de proximitat.'),
    (312, 'You can see all empty locals at the time your bid ends by clicking the corresponding button in order to organize an opening ceremony. All empty locals will be shown in a proximity range.'),
    (113, 'Los organismos públicos pueden publicar sus propias licitaciones desde el menú Licitaciones. Tan solo hace falta entrar todos los parámetros de forma válida y se creará al instante una nueva licitación.'),
    (213, 'Els organismes públics poden publicar les seves propies licitacions desde el menú Licitacions. Tan sols cal entrar tots els paràmetres de forma correcta i es crearà a l´instant una nova licitació.'),
    (313, 'Public organisms can publish their own biddings through the Licitacions menu. After correctly filling all the required input forms, the new licitation will be created.'),
    (114, 'El calendario de Google envía notificaciones al usuario en ciertas fechas señaladas, como: oferta superada, licitación acabada, licitación cercana a acabar.'),
    (214, 'El calendari intern envia notificacions a l´usuari en events marcats, com ara quan es supera una oferta, s´acaba una licitació o queda poc perquè acabi.'),
    (314, 'The calendar sends the user notifications in important parts of the process, such as whenever you get outbid or whenever the bidding is about to come to a close.');


INSERT INTO adj_relacio_articles(palabra, id_articulo)
VALUES
    ('licitar',	201),
    ('oferta',	201),
    ('puja',	201),
    ('pujar',	101),
    ('subhasta',	201),
    ('subasta',	101),
    ('tender',	301),
    ('bid',	301),
    ('bidding',	301),
    ('cor',	202),
    ('favorit',	202),
    ('desar',	202),
    ('corazon',	102),
    ('estrella',	102),
    ('favorito',	102),
    ('favoritos',	102),
    ('guardar',	102),
    ('perfil',	203),
    ('profile',	303),
    ('valoracio',	204),
    ('valoracion',	104),
    ('rating',	304),
    ('valorar',	204),
    ('nota',	204),
    ('mark',	304),
    ('ajustes',	105),
    ('opciones',	105),
    ('opcions',	205),
    ('settings',	305),
    ('idioma',	206),
    ('lengua',	106),
    ('llengua',	206),
    ('language',	306),
    ('cercar',	207),
    ('cerca',	207),
    ('buscar', 	107),
    ('busqueda',	107),
    ('filtre',	207),
    ('filtrar',	207),
    ('calendari', 208),
    ('calendario',	108),
    ('map',	309),
    ('mapa',	209),
    ('maps',	209),
    ('bloquejada',	210),
    ('blocked',	310),
    ('bloqueada',	110),
    ('block',	310),
    ('bloqueo',	110),
    ('bloqueig',	210),
    ('contrassenya',	211),
    ('contrasenya',	211),
    ('contraseña',	111),
    ('password',	311),
    ('event',	212),
    ('evento',	112),
    ('opening',	312),
    ('apertura',	112),
    ('abertura',	212),
    ('publicar', 213),
    ('publicacio', 213),
    ('publicacion', 113),
    ('offer', 313),
    ('notification',314),
    ('notificacion', 114),
    ('notificacio', 214),
    ('notifications',314),
    ('notificacions', 114),
    ('notificaciones', 214);